"""`branch-services.yaml` — which services a branch may omit, and what else
must go with them (spec §7.2, decision D9).

Why a manifest and not a set of `--no-<service>` flags
-----------------------------------------------------
The user's Chunk 2 request was that whatever implements exclusions be trivially
extendable to new services later. A flag is code: a new one means a new argparse
argument, a new branch in the renderer and a new test. A manifest entry is data,
and nothing in this module names a service. Adding a newly excludable container
is a YAML block in `branch-services.yaml` and nothing else, anywhere.

Why the closure is mandatory rather than tidy
---------------------------------------------
Measured on Compose v5.3.1, with the branch overlay applied:

    $ printf 'services:\\n  forgejo:\\n    profiles: [excluded]\\n' > ex.yml
    $ docker compose -f compose.yml -f compose.branch.yml -f ex.yml config
    service "forgejo-mcp" depends on undefined service "forgejo":
    invalid compose project
    exit 1

A `depends_on` target behind an inactive profile does not leave a dangling
reference for later — it invalidates the **whole project**, for `config`, `up`
and `down` alike. So `also_exclude` is a correctness requirement, and
`dangling_dependents()` derives the same rule from the resolved compose graph
so the manifest cannot go stale without a test noticing.

How exclusion is expressed
--------------------------
As a Compose profile, so Compose performs the omission natively rather than
this module editing service definitions. `render_exclusion_overlay()` emits a
per-branch `compose.exclude.yml` giving every excluded service
``profiles: [excluded]``; the branch's `COMPOSE_PROFILES` (Task 2) never names
that profile, so those services resolve away.

The direction matters and both failure modes are silent, so both are tested:

* if `EXCLUDED_PROFILE` ever reached `COMPOSE_PROFILES`, every "excluded"
  service would come back and the exclusion would do nothing;
* if `COMPOSE_PROFILES` named `agents`, every developer's agent would start
  (spec D7) — Task 2's `inherited_hazards` rule 3 already refuses that, and
  `profiles_for()` is checked here for never emitting it.

The opt-OUT direction is deliberate. The opposite scheme — give every excludable
service a profile in the committed overlay and have the branch activate the ones
it keeps — also works, but its failure mode is a branch that silently comes up
with holes in it, whereas this one's failure mode is a branch that comes up
whole. See the Task 4 ledger entry.

Stdlib + pyyaml only (decision D-A).
"""

from __future__ import annotations

import re
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path

import yaml

from aurora_cli import identity

MANIFEST_NAME = "branch-services.yaml"

#: The per-branch overlay this module renders. NOT committed and NOT generic:
#: which services a branch omits is a property of that branch, unlike
#: `compose.branch.yml` which is identical for all of them. `branch up` writes
#: it into the branch worktree next to the rendered `.env`.
EXCLUSION_OVERLAY_NAME = "compose.exclude.yml"

#: The profile an excluded service is parked behind. One shared name rather
#: than one per service: the branch never activates it, so a second name would
#: be a second thing to keep out of COMPOSE_PROFILES for no gain.
EXCLUDED_PROFILE = "excluded"

#: Every placeholder `on_exclude.env` may use. Each resolves through Task 1, so
#: no value in the manifest can name production as a literal.
_PLACEHOLDER_PATTERN = re.compile(r"\{([a-z_]+)\}")

_KNOWN_ENTRY_KEYS = frozenset({"excludable", "also_exclude", "on_exclude", "why"})
_KNOWN_ON_EXCLUDE_KEYS = frozenset({"env"})

_HEADER = """\
# GENERATED by `aurora branch up --without …` — do not edit, do not commit.
#
# Parks every excluded service behind the `{profile}` Compose profile, which the
# branch's COMPOSE_PROFILES never activates. Compose then omits the service
# natively.
#
# The list below is the TRANSITIVE closure of what was asked for
# (`branch-services.yaml: also_exclude`). It has to be: a service whose
# `depends_on` target sits behind an inactive profile makes the whole project
# invalid, so an incomplete closure is a hard `docker compose` failure and not
# a loose end.
"""


class ExclusionError(ValueError):
    """The exclusion manifest is malformed, or an exclusion cannot be honoured.

    One type for both, on purpose, because the distinction that matters to a
    caller is the MESSAGE. Every guard below names the service and says what is
    wrong with it; several guards raise this type from the same function, so a
    bare ``pytest.raises(ExclusionError)`` proves nothing about which one fired
    and the tests assert on the message instead.
    """


# ---------------------------------------------------------------------------
# the manifest
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ServiceRule:
    """One entry of `branch-services.yaml`."""

    name: str
    excludable: bool
    also_exclude: tuple[str, ...] = ()
    env: Mapping[str, str] = field(default_factory=dict)
    why: str = ""


def manifest_path() -> Path:
    return identity.package_root() / MANIFEST_NAME


def load_manifest(path: Path | None = None) -> dict[str, ServiceRule]:
    """Load and validate `branch-services.yaml`.

    Strict, because this file is the whole feature and every loose reading of
    it fails silently:

    * `excludable:` must be present and boolean. Defaulting it either way is
      wrong — default `true` and a service nobody thought about becomes
      removable, default `false` and adding an entry does nothing. Same rule,
      and the same reasoning, as `branch-env.yaml`'s `fatal:`.
    * an `excludable: false` entry must carry `why:`. The refusal message
      quotes it; a refusal with no reason is a wall, and the next reader
      deletes the entry rather than the wall.
    * unknown keys are refused. `also_excludes:` is a plausible typo that
      would otherwise parse cleanly and exclude nothing.
    * `on_exclude.env` placeholders are checked HERE, at load time, so a typo
      is a manifest error rather than a `{producton_url}/git` written into a
      branch `.env`.
    """
    path = path or manifest_path()
    if not path.is_file():
        raise ExclusionError(f"No exclusion manifest at {path}.")
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(document, Mapping) or "services" not in document:
        raise ExclusionError(f"{path} has no top-level `services:` mapping.")
    entries = document["services"]
    if not isinstance(entries, Mapping) or not entries:
        raise ExclusionError(f"{path} declares an empty `services:` mapping.")

    rules: dict[str, ServiceRule] = {}
    for name, entry in entries.items():
        where = f"{path}: {name}"
        if not isinstance(name, str) or not name.strip():
            raise ExclusionError(f"{path} has a service key that is not a name: {name!r}")
        if not isinstance(entry, Mapping):
            raise ExclusionError(f"{where} is not a mapping: {entry!r}")

        unknown = sorted(set(entry) - _KNOWN_ENTRY_KEYS)
        if unknown:
            raise ExclusionError(
                f"{where} declares unknown key(s) {unknown}. Known keys are "
                f"{sorted(_KNOWN_ENTRY_KEYS)}. A misspelt key would parse "
                "cleanly and exclude nothing."
            )

        if "excludable" not in entry:
            raise ExclusionError(
                f"{where} does not declare `excludable:`. Whether a service may "
                "be removed from a branch is the one question this manifest "
                "exists to answer, and it is not defaulted — say "
                "`excludable: true` or `excludable: false` explicitly."
            )
        excludable = entry["excludable"]
        if not isinstance(excludable, bool):
            raise ExclusionError(
                f"{where} declares `excludable: {excludable!r}`, which is not a "
                "boolean."
            )

        why = entry.get("why", "")
        if not isinstance(why, str):
            raise ExclusionError(f"{where} declares a non-string `why:`: {why!r}")
        why = " ".join(why.split())
        if not excludable and not why:
            raise ExclusionError(
                f"{where} is `excludable: false` but carries no `why:`. The "
                "refusal message quotes it, and a refusal with no reason is a "
                "wall the next reader removes instead of respecting."
            )

        also = entry.get("also_exclude", [])
        if isinstance(also, str) or not isinstance(also, Sequence):
            raise ExclusionError(
                f"{where} declares `also_exclude: {also!r}`, which is not a list."
            )
        for item in also:
            if not isinstance(item, str) or not item.strip():
                raise ExclusionError(
                    f"{where} lists {item!r} in `also_exclude`, which is not a "
                    "service name."
                )
        if name in also:
            raise ExclusionError(
                f"{where} lists itself in `also_exclude`; the closure already "
                "includes the service that was asked for."
            )
        if len(set(also)) != len(also):
            raise ExclusionError(f"{where} repeats a name in `also_exclude`: {also!r}")

        on_exclude = entry.get("on_exclude", {}) or {}
        if not isinstance(on_exclude, Mapping):
            raise ExclusionError(
                f"{where} declares `on_exclude: {on_exclude!r}`, which is not a "
                "mapping."
            )
        unknown = sorted(set(on_exclude) - _KNOWN_ON_EXCLUDE_KEYS)
        if unknown:
            raise ExclusionError(
                f"{where} declares unknown `on_exclude` key(s) {unknown}; only "
                f"{sorted(_KNOWN_ON_EXCLUDE_KEYS)} is understood."
            )
        env = on_exclude.get("env", {}) or {}
        if not isinstance(env, Mapping):
            raise ExclusionError(
                f"{where} declares `on_exclude.env: {env!r}`, which is not a "
                "mapping."
            )
        resolved_env: dict[str, str] = {}
        for key, value in env.items():
            if not isinstance(key, str) or not key.strip():
                raise ExclusionError(
                    f"{where} has an `on_exclude.env` key that is not a variable "
                    f"name: {key!r}"
                )
            if not isinstance(value, str):
                raise ExclusionError(
                    f"{where}: `on_exclude.env.{key}` is {value!r}, not a string."
                )
            for placeholder in _PLACEHOLDER_PATTERN.findall(value):
                if placeholder not in _SUBSTITUTIONS:
                    raise ExclusionError(
                        f"{where}: `on_exclude.env.{key}` uses unknown "
                        f"placeholder {{{placeholder}}}. Known: "
                        f"{sorted(_SUBSTITUTIONS)}."
                    )
            resolved_env[key] = value

        rules[name] = ServiceRule(
            name=name,
            excludable=excludable,
            also_exclude=tuple(also),
            env=resolved_env,
            why=why,
        )
    return rules


def _manifest(manifest: Mapping[str, ServiceRule] | None) -> Mapping[str, ServiceRule]:
    return load_manifest() if manifest is None else manifest


def excludable_services(
    manifest: Mapping[str, ServiceRule] | None = None,
) -> list[str]:
    """Services `--without` accepts by name."""
    return sorted(n for n, rule in _manifest(manifest).items() if rule.excludable)


def manifest_services(
    manifest: Mapping[str, ServiceRule] | None = None,
) -> set[str]:
    """Every service name the manifest mentions, as a key or in `also_exclude`.

    This is the set that must be real compose SERVICE KEYS — the
    `affine_server`-vs-`affine` mistake lives in the `also_exclude` lists just
    as easily as in the keys.
    """
    manifest = _manifest(manifest)
    names = set(manifest)
    for rule in manifest.values():
        names.update(rule.also_exclude)
    return names


# ---------------------------------------------------------------------------
# the closure
# ---------------------------------------------------------------------------


def closure(
    names: Iterable[str], manifest: Mapping[str, ServiceRule] | None = None
) -> set[str]:
    """Every service that must go when `names` go — to a fixed point.

    Transitive: `a` pulling in `b` which pulls in `c` pulls in `c`. Iterative
    with a `seen` set rather than recursive, so a manifest containing a cycle
    (`a → b → a`, however it got written) terminates instead of blowing the
    stack. Names with no manifest entry are kept — being pulled in
    transitively does not require an entry of your own.
    """
    manifest = _manifest(manifest)
    seen: set[str] = set()
    pending = list(names)
    while pending:
        name = pending.pop()
        if name in seen:
            continue
        seen.add(name)
        rule = manifest.get(name)
        if rule is not None:
            pending.extend(rule.also_exclude)
    return seen


def validate_excludable(
    names: Iterable[str], manifest: Mapping[str, ServiceRule] | None = None
) -> None:
    """Refuse anything the manifest does not mark `excludable: true`.

    Two distinct refusals, deliberately carrying different messages:
    a service the manifest never heard of, and a service it protects. Only the
    services named directly by `--without` come through here — `also_exclude`
    members are pulled in by the closure and are not required to be excludable
    in their own right, which is what lets `postgres` go with `affine` while
    `--without postgres` is still refused.
    """
    manifest = _manifest(manifest)
    for name in names:
        rule = manifest.get(name)
        if rule is None:
            raise ExclusionError(
                f"{name!r} is not listed in {MANIFEST_NAME}, so there is no "
                "record of what else would have to go with it. Services that "
                f"may be excluded: {excludable_services(manifest)}."
            )
        if not rule.excludable:
            raise ExclusionError(
                f"{name!r} cannot be excluded from a branch: {rule.why}"
            )


def dangling_dependents(
    excluded: Iterable[str], config: Mapping
) -> dict[str, list[str]]:
    """Services left in the branch whose `depends_on` names an excluded one.

    Anything here is a hard `docker compose` failure — "depends on undefined
    service … : invalid compose project" — so a non-empty result means the
    closure in `branch-services.yaml` is short.

    Derived from the RESOLVED compose configuration, never from the manifest,
    which is the whole point: if this read the same `also_exclude` lists the
    closure reads, deleting an entry would blind the closure and the check in
    one stroke.
    """
    services = config.get("services") or {}
    if not services:
        raise ExclusionError(
            "the resolved compose configuration declares no services, so a "
            "dangling-dependent check over it would pass vacuously. Check that "
            '`docker compose config` ran in the repo root with COMPOSE_PROFILES="*".'
        )
    excluded = set(excluded)
    dangling: dict[str, list[str]] = {}
    for name, body in services.items():
        if name in excluded:
            continue
        depends = (body or {}).get("depends_on") or {}
        missing = sorted(set(depends) & excluded)
        if missing:
            dangling[name] = missing
    return dangling


# ---------------------------------------------------------------------------
# profiles
# ---------------------------------------------------------------------------


def profiles_for(
    excluded: Iterable[str], manifest: Mapping[str, ServiceRule] | None = None
) -> str:
    """The Compose profile list an excluded service is parked behind.

    Comma-separated, matching `COMPOSE_PROFILES`' own spelling, so a future
    scheme can widen it without changing the renderer. Empty when nothing is
    excluded — and empty is load-bearing, not cosmetic: a service rendered with
    `profiles: []` has NO profile and therefore always starts, so this
    returning `""` for a non-empty exclusion set would produce an overlay that
    excludes nothing while looking exactly right.

    Never emits `agents`. That profile starts every developer's agent (spec
    D7), and the branch `.env`'s COMPOSE_PROFILES is the union of this and the
    per-developer profiles — so a collision here would be a silent
    over-provisioning rather than an error.
    """
    return EXCLUDED_PROFILE if closure(excluded, manifest) else ""


def branch_profiles(
    agent_profiles: str | Iterable[str] = (),
    excluded: Iterable[str] = (),
    manifest: Mapping[str, ServiceRule] | None = None,
) -> str:
    """The branch's COMPOSE_PROFILES: the agent profiles, and nothing else.

    Exists so the union is written down once and can be asserted on, rather
    than being an unwritten assumption. Under the opt-out scheme the exclusion
    machinery contributes NOTHING to COMPOSE_PROFILES — it removes services by
    parking them behind a profile that is never activated — and this function
    refuses to let `EXCLUDED_PROFILE` in, because if it ever appeared every
    excluded service would come straight back with no error anywhere.
    """
    if isinstance(agent_profiles, str):
        wanted = [p.strip() for p in agent_profiles.split(",") if p.strip()]
    else:
        wanted = [p.strip() for p in agent_profiles if p.strip()]
    parked = {p for p in profiles_for(excluded, manifest).split(",") if p}
    collision = sorted(set(wanted) & parked)
    if collision:
        raise ExclusionError(
            f"COMPOSE_PROFILES would activate {collision}, which is where the "
            "excluded services are parked; every one of them would come back "
            "and the exclusion would silently do nothing."
        )
    return ",".join(wanted)


# ---------------------------------------------------------------------------
# on_exclude.env
# ---------------------------------------------------------------------------


def _production_url() -> str:
    return f"https://{identity.production_domain()}"


#: Every placeholder, and where its value comes from. All of them route through
#: `identity`, so production's hostname appears in neither this file nor the
#: manifest — the same rule Task 1 and Task 2 hold themselves to, for the same
#: reason: a literal is correct on exactly one host.
_SUBSTITUTIONS = {
    "production_url": _production_url,
    "production_domain": identity.production_domain,
}


def _substitute(value: str) -> str:
    for name, resolve in _SUBSTITUTIONS.items():
        token = "{" + name + "}"
        if token in value:
            value = value.replace(token, resolve())
    leftover = _PLACEHOLDER_PATTERN.findall(value)
    if leftover:
        raise ExclusionError(
            f"{value!r} still contains unresolved placeholder(s) {leftover}."
        )
    return value


def env_overrides_for(
    excluded: Iterable[str], manifest: Mapping[str, ServiceRule] | None = None
) -> dict[str, str]:
    """`on_exclude.env` for the whole closure, with placeholders resolved.

    Handed to `envfile.render_branch_env(exclusions_env=…)`, which applies it
    LAST so the result is still seen by every hazard rule in Task 2's checker.

    Two rules that disagree about one variable is a manifest bug, not a
    last-one-wins: the branch would be wired one way or the other depending on
    dictionary order.
    """
    manifest = _manifest(manifest)
    overrides: dict[str, str] = {}
    origin: dict[str, str] = {}
    for name in sorted(closure(excluded, manifest)):
        rule = manifest.get(name)
        if rule is None:
            continue
        for key, raw in rule.env.items():
            value = _substitute(raw)
            if key in overrides and overrides[key] != value:
                raise ExclusionError(
                    f"excluding {sorted(set(excluded))} sets {key} to both "
                    f"{overrides[key]!r} (from {origin[key]}) and {value!r} "
                    f"(from {name}); the manifest must not disagree with itself."
                )
            overrides[key] = value
            origin[key] = name
    return overrides


def production_reference_exemptions(
    excluded: Iterable[str],
    manifest: Mapping[str, ServiceRule] | None = None,
    domain: str | None = None,
) -> frozenset[str]:
    """Variables this exclusion set deliberately points at production.

    Task 2's `inherited_hazards` rule 1 refuses ANY branch variable whose value
    embeds production's domain, and that refusal is the most valuable thing in
    Task 2 (finding N1). `--without forgejo` is the one case where naming
    production is the intent rather than the bug (spec §5.4), so the exemption
    is derived from the values actually produced — never a hand-kept list — and
    it is EMPTY whenever nothing is excluded.
    """
    domain = domain or identity.production_domain()
    return frozenset(
        key
        for key, value in env_overrides_for(excluded, manifest).items()
        if domain in value
    )


# ---------------------------------------------------------------------------
# the per-branch overlay
# ---------------------------------------------------------------------------


def render_exclusion_overlay(
    services: Iterable[str], manifest: Mapping[str, ServiceRule] | None = None
) -> str:
    """The text of `compose.exclude.yml` for an ALREADY-CLOSED set of services.

    Takes the closed set rather than closing it internally, so that a test can
    render exactly what an incomplete closure would produce and hand it to real
    Compose. `exclusion_overlay_for()` is the ergonomic entry point that closes
    first, and is what `branch up` should call.

    `services: {}` is emitted for an empty set rather than a bare `services:`
    key — Compose refuses the latter with "services must be a mapping".
    """
    parked = sorted(set(services))
    profiles = [p for p in profiles_for(parked, manifest).split(",") if p]
    lines = [_HEADER.format(profile=EXCLUDED_PROFILE)]
    if not parked:
        lines.append("services: {}")
    else:
        lines.append("services:")
        for name in parked:
            lines.append(f"  {name}:")
            lines.append(f"    profiles: [{', '.join(profiles)}]")
    return "\n".join(lines).rstrip("\n") + "\n"


def exclusion_overlay_for(
    excluded: Iterable[str], manifest: Mapping[str, ServiceRule] | None = None
) -> str:
    """`render_exclusion_overlay(closure(excluded))` — what `branch up` wants."""
    return render_exclusion_overlay(closure(excluded, manifest), manifest)


def exclusion_overlay_path(directory: Path) -> Path:
    return Path(directory) / EXCLUSION_OVERLAY_NAME


def write_exclusion_overlay(
    services: Iterable[str],
    directory: Path,
    manifest: Mapping[str, ServiceRule] | None = None,
) -> Path:
    """Write the overlay for an already-closed set into `directory`.

    Written ALWAYS, even when nothing is excluded, because Compose's `-f` is a
    hard error on a missing file (trap 4) and a caller that has to decide
    whether to pass `-f` is a caller that will get it wrong once.
    """
    path = exclusion_overlay_path(directory)
    path.write_text(render_exclusion_overlay(services, manifest), encoding="utf-8")
    return path
