import yaml

from dev_administration.agents_compose import (
    HERMES_IMAGE, agent_specs, render_agents_compose,
)
from dev_administration.models import DeveloperConfig

DEVS = [
    DeveloperConfig(username="juan", display_name="Juan", forgejo_user="juan"),
    DeveloperConfig(username="ethan", display_name="Ethan", forgejo_user="ethan"),
]


def test_agent_specs_allocate_sequential_ports():
    specs = agent_specs(DEVS, base_port=9120)
    assert [s.host_port for s in specs] == [9120, 9121]
    assert [s.service for s in specs] == ["hermes-juan", "hermes-ethan"]
    assert [s.container_name for s in specs] == ["hermes-juan", "hermes-ethan"]
    assert [s.volume for s in specs] == ["hermes-juan-home", "hermes-ethan-home"]


def test_agent_specs_publish_nothing_when_asked():
    """A branch publishes no host ports at all (spec §5.1): port collision
    becomes unrepresentable rather than merely avoided."""
    specs = agent_specs(DEVS, base_port=9120, publish_ports=False)
    assert [s.host_port for s in specs] == [None, None]


def test_agent_specs_carry_both_profiles():
    assert agent_specs(DEVS)[0].profiles == ("agents", "agent-juan")


def test_render_is_valid_yaml_with_one_service_per_developer():
    doc = yaml.safe_load(render_agents_compose(agent_specs(DEVS)))
    assert sorted(doc["services"]) == ["hermes-ethan", "hermes-juan"]
    assert sorted(doc["volumes"]) == ["hermes-ethan-home", "hermes-juan-home"]


def test_rendered_service_is_compose_managed_not_docker_run():
    """The whole point of M4: without this, `docker compose down` cannot see
    a developer's agent and a branch stack has no agents at all."""
    doc = yaml.safe_load(render_agents_compose(agent_specs(DEVS)))
    juan = doc["services"]["hermes-juan"]
    # The pinned digest, from the generator, so the two cannot disagree --
    # and `@sha256:` asserted separately so pinning cannot be dropped and
    # the comparison still trivially pass against whatever it became.
    assert juan["image"] == HERMES_IMAGE
    assert "@sha256:" in juan["image"]
    assert juan["container_name"] == "hermes-juan"
    assert juan["command"] == "gateway run"
    assert juan["restart"] == "unless-stopped"
    assert juan["volumes"] == ["hermes-juan-home:/opt/data"]
    assert juan["ports"] == ["127.0.0.1:9120:9119"]
    assert juan["profiles"] == ["agents", "agent-juan"]


def test_rendered_service_carries_the_uvicorn_forwarded_ips_fix():
    """FORWARDED_ALLOW_IPS rode on the imperative `docker run` and is
    load-bearing: without it uvicorn ignores X-Forwarded-Proto, writes the
    session cookie without Secure AND under a different name, and the user
    ping-pongs between the dashboard and the sign-in page."""
    doc = yaml.safe_load(render_agents_compose(agent_specs(DEVS)))
    env = doc["services"]["hermes-juan"]["environment"]
    assert env["FORWARDED_ALLOW_IPS"] == "*"
    assert env["HERMES_HOME"] == "/opt/data"
    assert env["HERMES_DASHBOARD_HOST"] == "0.0.0.0"
    assert env["HERMES_DASHBOARD_PUBLIC_URL"] == "https://${DOMAIN_NAME}/agent/juan"


def test_rendered_service_reads_its_secrets_from_an_optional_env_file():
    """OIDC client id/secret are per-install secrets written by reconcile.
    They must not enter a committed file, and the reference must be optional
    so a fresh worktree still resolves `docker compose config` before
    reconcile has ever run (probed: absent optional env_file, exit 0)."""
    body = render_agents_compose(agent_specs(DEVS))
    doc = yaml.safe_load(body)
    assert doc["services"]["hermes-juan"]["env_file"] == [
        {"path": "./.agent-env/juan.env", "required": False}
    ]
    assert "CLIENT_SECRET" not in body


def test_render_has_no_host_ports_in_service_mode():
    doc = yaml.safe_load(render_agents_compose(agent_specs(DEVS, publish_ports=False)))
    assert "ports" not in doc["services"]["hermes-juan"]
    assert doc["services"]["hermes-juan"]["expose"] == ["9119"]


def test_render_is_deterministic():
    """The drift test compares bytes, so ordering must be stable."""
    assert render_agents_compose(agent_specs(DEVS)) == render_agents_compose(agent_specs(DEVS))


def test_render_announces_that_it_is_generated():
    body = render_agents_compose(agent_specs(DEVS))
    assert body.startswith("# GENERATED by `dev-admin render-agents`")
    assert "do not edit" in body


def test_render_of_no_developers_is_still_valid_compose():
    doc = yaml.safe_load(render_agents_compose([]))
    assert doc["services"] == {}
    assert doc["volumes"] == {}


def test_interpolation_placeholders_survive_a_yaml_round_trip():
    """Not in the task brief; added because the renderer emits ${VAR} as
    UNQUOTED plain scalars and the drift test only ever compares bytes.

    `${FORGEJO_URL}` opens with `$` and contains braces. In block context
    YAML permits both, so it loads as the literal string Compose will later
    interpolate -- but that is a property of the emitted quoting style, not
    of the values, and a future reordering that pushed one of these into a
    flow context would turn it into a parse error or a dict. Pinning it here
    means the renderer's quoting cannot regress silently.
    """
    doc = yaml.safe_load(render_agents_compose(agent_specs(DEVS)))
    env = doc["services"]["hermes-juan"]["environment"]
    assert env["FORGEJO_URL"] == "${FORGEJO_URL}"
    assert env["HERMES_DASHBOARD_OIDC_ISSUER"] == "${FORGEJO_URL}"
    assert env["HERMES_DASHBOARD"] == "1", (
        "must stay the STRING '1' -- an unquoted 1 loads as an int and "
        "Compose rejects a non-string environment value"
    )
