"""Render per-developer Hermes agents as Compose services (spec M4).

Before this, agents were created by `docker run` in docker_utils, so they
carried no compose project label at all. Consequences, all verified on the
host: `docker compose down` could not see them, `--remove-orphans` could not
remove them, and a branch stack would have had no agents whatsoever.

The output is COMMITTED, not gitignored: Compose's `include:` is a hard
failure on a missing file, so a generated-but-absent fragment would break
`docker compose config` in every fresh worktree — precisely the property
Chunk 1 exists to guarantee. Drift is caught by
tests/test_repo_conformance.py::test_agents_compose_matches_developers_yaml.
"""

from __future__ import annotations

from dataclasses import dataclass

from dev_administration.models import DeveloperConfig

HERMES_IMAGE = (
    "nousresearch/hermes-agent:latest@sha256:bbe5076a990ba59afb6c6ee9bb1084a26b801b732b9fb82a18de862d226e59b4"
)
DEFAULT_BASE_PORT = 9120  # 9119 is the admin agent's dashboard
AGENT_ENV_DIR = "./.agent-env"

_HEADER = """\
# GENERATED by `dev-admin render-agents` from developers.yaml — do not edit.
#
# Regenerate after ANY change to developers.yaml:
#     dev-admin render-agents
# tests/test_repo_conformance.py::test_agents_compose_matches_developers_yaml
# fails if this file and developers.yaml disagree.
#
# Profiles: `agents` activates every developer (production sets
# COMPOSE_PROFILES=agents in .env); `agent-<username>` activates exactly one,
# which is how spec D7's `--devs` provisions only the requesting developer in
# a branch without editing any tracked file inside the worktree.
"""


@dataclass(frozen=True)
class AgentSpec:
    username: str
    display_name: str
    service: str
    container_name: str
    volume: str
    host_port: int | None
    profiles: tuple[str, ...]
    env_file: str


def agent_specs(
    devs: list[DeveloperConfig],
    base_port: int = DEFAULT_BASE_PORT,
    publish_ports: bool = True,
) -> list[AgentSpec]:
    """One spec per developer, ports allocated in developers.yaml order.

    `publish_ports=False` is the branch case: spec §5.1 requires a branch to
    publish no host ports at all, so collision with production is
    unrepresentable rather than merely avoided.
    """
    return [
        AgentSpec(
            username=dev.username,
            display_name=dev.display_name,
            service=f"hermes-{dev.username}",
            container_name=f"hermes-{dev.username}",
            volume=f"hermes-{dev.username}-home",
            host_port=(base_port + index) if publish_ports else None,
            profiles=("agents", f"agent-{dev.username}"),
            env_file=f"{AGENT_ENV_DIR}/{dev.username}.env",
        )
        for index, dev in enumerate(devs)
    ]


def render_agents_compose(
    specs: list[AgentSpec],
    domain_var: str = "DOMAIN_NAME",
) -> str:
    """Render the Compose fragment.

    Hand-written YAML rather than yaml.dump so ${VAR} interpolation, comments
    and key order survive byte-for-byte — the drift test compares bytes.
    """
    if not specs:
        return _HEADER + "\nservices: {}\n\nvolumes: {}\n"

    lines: list[str] = [_HEADER, "services:"]
    for spec in specs:
        lines.extend([
            f"  {spec.service}:",
            f"    image: {HERMES_IMAGE}",
            f"    container_name: {spec.container_name}",
            "    profiles: [" + ", ".join(f'"{p}"' for p in spec.profiles) + "]",
            "    restart: unless-stopped",
            "    command: gateway run",
            "    volumes:",
            f"      - {spec.volume}:/opt/data",
            "    environment:",
            "      HERMES_HOME: /opt/data",
            '      HERMES_DASHBOARD: "1"',
            "      HERMES_DASHBOARD_HOST: 0.0.0.0",
            f"      HERMES_DASHBOARD_PUBLIC_URL: https://${{{domain_var}}}/agent/{spec.username}",
            "      FORGEJO_URL: ${FORGEJO_URL}",
            "      HERMES_DASHBOARD_OIDC_ISSUER: ${FORGEJO_URL}",
            # uvicorn only honours X-Forwarded-* from peers in
            # forwarded_allow_ips (default 127.0.0.1). Caddy reaches this
            # container from the bridge gateway, so without this uvicorn sees
            # scheme=http, writes the session cookie without Secure and under
            # a different NAME (__Secure- prefix), and the session written at
            # login is not read back — the user ping-pongs between the
            # dashboard and the sign-in page.
            '      FORWARDED_ALLOW_IPS: "*"',
            "    env_file:",
            # OIDC client id/secret are per-install secrets written by
            # `dev-admin reconcile`. required: false so a fresh worktree still
            # resolves `docker compose config` before reconcile has ever run.
            f"      - path: {spec.env_file}",
            "        required: false",
            "    expose:",
            '      - "9119"',
        ])
        if spec.host_port is not None:
            lines.extend([
                "    ports:",
                f'      - "127.0.0.1:{spec.host_port}:9119"',
            ])
        lines.append("")
    lines.append("volumes:")
    lines.extend(f"  {spec.volume}:" for spec in specs)
    return "\n".join(lines).rstrip() + "\n"
