from __future__ import annotations

import html
import json
import os
import subprocess
from typing import Literal

from dev_administration.models import DeveloperConfig
from dev_administration.project import assert_same_project


# Top-level dashboard paths Hermes may redirect to WITHOUT the proxy prefix.
# Used to build an RE2-safe (no lookahead) Location-rewrite alternation.
_TOP_LEVEL_PATHS = (
    "login", "sessions", "chat", "settings", "skills",
    "cron", "profiles", "tools", "memory", "files",
)
_TOP_LEVEL_RE = "|".join(_TOP_LEVEL_PATHS)

UpstreamMode = Literal["published", "service"]

# Production's Caddy is network_mode: host — it cannot resolve Docker DNS, so
# every backend must be reached on a published 127.0.0.1 port. A branch's
# Caddy is network_mode: service:tailscale (spec §4.2): it shares the
# sidecar's network namespace, 127.0.0.1 reaches nothing there, and the branch
# publishes no host ports at all. Same generator, two address spaces.
_FJELL_PORT = 9080
_AUTHZ_PORT = 9140
_AGENT_PORT = 9119


def _check_mode(mode: str) -> None:
    if mode not in ("published", "service"):
        raise ValueError(
            f"Unknown upstream mode {mode!r}; expected 'published' or 'service'"
        )


def agent_upstream(dev: dict, mode: UpstreamMode = "published") -> str:
    _check_mode(mode)
    if mode == "service":
        return f"hermes-{dev['username']}:{_AGENT_PORT}"
    return f"127.0.0.1:{dev.get('host_port', _AGENT_PORT)}"


def fjell_upstream(mode: UpstreamMode = "published") -> str:
    _check_mode(mode)
    return f"fjell:{_FJELL_PORT}" if mode == "service" else f"127.0.0.1:{_FJELL_PORT}"


def authz_upstream(mode: UpstreamMode = "published") -> str:
    _check_mode(mode)
    return (
        f"agent-authz:{_AUTHZ_PORT}" if mode == "service"
        else f"127.0.0.1:{_AUTHZ_PORT}"
    )


def generate_caddy_agents_conf(
    devs: list[dict], domain: str, mode: UpstreamMode = "published",
) -> str:
    """Generate Caddy route blocks for per-developer agent dashboards.

    Each dev dict needs: username, host_port (int; published mode only).

    `mode` selects the address space:
      published — 127.0.0.1:<host_port>, for production's host-networked Caddy
      service   — hermes-<user>:9119, for a branch's Caddy sharing the
                  tailscale sidecar's netns, where 127.0.0.1 reaches nothing
    """
    _check_mode(mode)
    blocks = [
        "# Generated by dev-admin reconcile — do not edit manually",
        "",
    ]
    for dev in devs:
        name = dev["username"]
        agent_addr = agent_upstream(dev, mode)
        blocks.extend([
            # Rescue route for UNPREFIXED auth paths.
            #
            # The server-rendered login page hardcodes
            #   <a href="/auth/login?provider=...">
            # (hermes_cli/dashboard_auth/login_page.py). Unlike the redirect
            # Location headers below, this link is inside the HTML BODY, so
            # header rewriting cannot reach it, and render_login_html() takes
            # no prefix argument — there is no upstream-free way to fix it in
            # Hermes. Without this block the button lands on the site root,
            # which is the basic-auth-protected fjell default handler, and
            # the user gets a 404.
            #
            # Match on Referer: these paths carry no prefix and the session
            # cookies are scoped to Path=/agent/<user>, so the referring page
            # is the only signal identifying which developer is signing in.
            f"@auth_escape_{name} {{",
            "    path /auth/login /auth/login/* /auth/callback /auth/callback/*",
            # header_regexp, not `header Referer *//*/agent/<u>/*`: the glob
            # form anchors awkwardly against a full URL and did not match in
            # practice. A regexp on the path portion is unambiguous.
            f'    header_regexp Referer "/agent/{name}(/|$)"',
            "}",
            # Top-level `redir @matcher`, NOT `handle @matcher { redir ... }`.
            # Inside a handle block the redirect emitted an empty 200 with no
            # Location header. Also use {http.request.uri} — the short {uri}
            # placeholder resolves empty here, silently producing a redirect
            # to the bare prefix and losing the query string.
            f"redir @auth_escape_{name} /agent/{name}{{http.request.uri}} 302",
            "",
            f"handle /agent/{name}/setup {{",
            f"    reverse_proxy {fjell_upstream(mode)}",
            "}",
            "",
            f"handle_path /agent/{name}/* {{",
            # AUTHORIZATION. Hermes authenticates but does not authorize, so
            # without this any valid Forgejo account could open this agent.
            # agent-authz verifies the session JWT and checks the caller owns
            # this agent.
            #
            # Only 403 (valid session, WRONG user) is intercepted. A 401 must
            # fall through to Hermes untouched so its own auto-SSO can start
            # the OIDC round trip — intercepting it here (even to redirect to
            # /login) breaks first-time sign-in, because nobody has a session
            # before authenticating. /auth/*, /login and the favicon are
            # exempt for the same reason.
            "    @needs_authz not path /auth/* /login /favicon.ico",
            f"    forward_auth @needs_authz {authz_upstream(mode)} {{",
            f"        uri /auth?agent={name}",
            "        copy_headers X-Authz-Reason",
            # forward_auth treats any non-2xx as a denial and copies the
            # response through. Re-issue 401 as a pass-through by handling
            # ONLY 403 here and letting 401 continue to the backend.
            "        @wrong_user status 403",
            "        handle_response @wrong_user {",
            # Serve the HTML page but keep the status at 403. `file_server`
            # alone answers 200, which made api/sessions look successful
            # while returning the denial page — a false pass in the isolation
            # test. Setting the status explicitly first keeps it honest.
            "            root * /etc/caddy/agent-denied",
            "            rewrite * /index.html",
            "            header Content-Type \"text/html; charset=utf-8\"",
            "            file_server {",
            "                status 403",
            "            }",
            "        }",
            "        @unauthenticated status 401",
            "        handle_response @unauthenticated {",
            f"            reverse_proxy {agent_addr} {{",
            f"                header_up X-Forwarded-Prefix /agent/{name}",
            "                header_up X-Forwarded-Proto https",
            f'                header_down Location "^/({_TOP_LEVEL_RE})(.*)$" "/agent/{name}/$1$2"',
            f'                header_down Location "^/$" "/agent/{name}/"',
            # Stale-cookie recovery must be repeated here. A garbage session
            # cookie makes agent-authz answer 401, which routes through this
            # inner proxy — without this block Hermes' 503 escapes as an
            # opaque error the user cannot clear.
            "                @stale status 503",
            "                handle_response @stale {",
            f'                    header Set-Cookie "__Secure-hermes_session_at=; Path=/agent/{name}; Max-Age=0; Secure"',
            f'                    header +Set-Cookie "__Secure-hermes_session_rt=; Path=/agent/{name}; Max-Age=0; Secure"',
            f'                    header +Set-Cookie "__Secure-hermes_session_provider=; Path=/agent/{name}; Max-Age=0; Secure"',
            f'                    header +Set-Cookie "hermes_session_at=; Path=/agent/{name}; Max-Age=0"',
            f'                    header +Set-Cookie "hermes_session_provider=; Path=/agent/{name}; Max-Age=0"',
            f"                    redir * /agent/{name}/login 302",
            "                }",
            "            }",
            "        }",
            "    }",
            f"    reverse_proxy {agent_addr} {{",
            f"        header_up X-Forwarded-Prefix /agent/{name}",
            # Set explicitly rather than relying on Caddy's defaults. Hermes
            # uses the forwarded scheme to decide the cookie Secure flag AND
            # the cookie name prefix; if it resolves to http the session
            # written at login is not read back and the user loops between
            # the dashboard and the sign-in page. Pair with
            # FORWARDED_ALLOW_IPS on the container, or uvicorn discards this.
            "        header_up X-Forwarded-Proto https",
            # Hermes' post-login redirect (routes.py: RedirectResponse(landing))
            # does NOT apply the X-Forwarded-Prefix, so it emits a bare "/" or
            # "/sessions". Un-prefixed those land on the site root (basic-auth
            # 401). Rewrite Location on the way out. RE2 has no lookahead, so
            # match an explicit set of known top-level dashboard paths.
            f'        header_down Location "^/({_TOP_LEVEL_RE})(.*)$" "/agent/{name}/$1$2"',
            f'        header_down Location "^/$" "/agent/{name}/"',
            # A stale/garbage value in the session cookie makes the OIDC
            # plugin raise ProviderError (PyJWT DecodeError is wrapped as
            # "provider unreachable"), surfacing as an opaque 503 the user
            # cannot clear without manually deleting cookies. Convert it to
            # a cookie-clearing bounce to the login route. Target the LOGIN
            # path, not "/", so the response is never the same URL that
            # produced it (that self-redirect loops for clients which replay
            # a fixed Cookie header).
            "        @stale_session status 503",
            "        handle_response @stale_session {",
            f'            header Set-Cookie "hermes_session_at=; Path=/agent/{name}; Max-Age=0"',
            f'            header +Set-Cookie "hermes_session_rt=; Path=/agent/{name}; Max-Age=0"',
            f'            header +Set-Cookie "hermes_session_provider=; Path=/agent/{name}; Max-Age=0"',
            f"            redir * /agent/{name}/login 302",
            "        }",
            "    }",
            "}",
            f"handle_path /agent/{name} {{",
            f"    reverse_proxy {agent_addr} {{",
            f"        header_up X-Forwarded-Prefix /agent/{name}",
            f'        header_down Location "^/$" "/agent/{name}/"',
            "    }",
            "}",
            "",
        ])
    # Fallback rescue for UNPREFIXED /auth/* with NO usable Referer.
    #
    # Browsers strip Referer on cross-origin navigations, so returning from
    # the Forgejo consent screen can hit /auth/login with no referring page.
    # The Referer matchers above then miss and the request falls through to
    # the site's default handler — a bare 404 from fjell, and a dead end in
    # the middle of signing in.
    #
    # These paths are meaningless outside an agent, so never let them reach
    # the portfolio. With exactly one developer the target is unambiguous;
    # with several we cannot know which agent the user meant, so render a
    # chooser instead of guessing.
    if devs:
        blocks.extend([
            "# Unprefixed /auth/* with no Referer — never fall through to the",
            "# portfolio's catch-all (see comment in caddy_utils.py).",
            "@auth_orphan {",
            "    path /auth/login /auth/login/* /auth/callback /auth/callback/*",
            "}",
        ])
        if len(devs) == 1:
            only = devs[0]["username"]
            blocks.extend([
                f"redir @auth_orphan /agent/{only}{{http.request.uri}} 302",
                "",
            ])
        else:
            # Several developers: we cannot know which agent the user meant,
            # so serve a chooser rather than guessing wrong. Written to a
            # file and served with file_server so the HTML never has to be
            # escaped through the Caddyfile's own quoting rules.
            blocks.extend([
                "handle @auth_orphan {",
                "    root * /etc/caddy/agent-chooser",
                "    rewrite * /index.html",
                "    file_server",
                "}",
                "",
            ])

    return "\n".join(blocks) + "\n"


def generate_agents_json(devs: list[DeveloperConfig]) -> str:
    """Generate the agents.json file for fjell's landing page."""
    data = [
        {"username": dev.username, "display_name": dev.display_name}
        for dev in devs
    ]
    return json.dumps(data, indent=2)


def reload_caddy(container_name: str) -> None:
    """Signal Caddy to reload its config.

    Guarded: a branch's reconcile reloading PRODUCTION's Caddy is the exact
    failure spec 5.3 names as the reason the guard exists.
    """
    assert_same_project(container_name)
    subprocess.run(
        ["docker", "exec", container_name, "caddy", "reload",
         "--config", "/etc/caddy/Caddyfile"],
        capture_output=True, text=True, check=False,
    )


def write_owners_map(path: str, devs: list[dict]) -> None:
    """Write the agent -> owner map consumed by the agent-authz service.

    Each entry pins an agent to exactly one Forgejo identity. ``owner_sub``
    (the numeric Forgejo user id) is preferred because usernames can be
    renamed and ids cannot; ``owner_username`` is the fallback for entries
    provisioned before the id was known. ``client_id`` lets the verifier
    check the ``aud`` claim, so a token minted for a DIFFERENT agent's OAuth2
    app cannot be replayed here.
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)
    owners = {
        d["username"]: {
            "owner_username": d.get("forgejo_user") or d["username"],
            "owner_sub": str(d.get("forgejo_sub") or ""),
            "client_id": d.get("client_id") or "",
        }
        for d in devs
    }
    tmp = f"{path}.tmp"
    with open(tmp, "w") as fh:
        json.dump(owners, fh, indent=2, sort_keys=True)
    os.replace(tmp, path)  # atomic: the reader never sees a partial file


def write_denied_page(container_name: str) -> None:
    """Write the 'not your agent' page served on a 403 from agent-authz."""
    assert_same_project(container_name)
    page = """<!doctype html>
<meta charset="utf-8">
<title>Not your agent</title>
<body style="font-family:system-ui;max-width:34rem;margin:15vh auto">
  <h1>This isn't your agent</h1>
  <p>You're signed in, but this agent belongs to another developer.
     Each agent is locked to the Forgejo account it was provisioned for.</p>
  <p>If you don't have an agent yet, ask an admin to provision one for your
     Forgejo account.</p>
  <p><a href="/auth/login">Go to your agent</a> &middot;
     <a href="/git/user/logout">Sign out</a></p>
</body>
"""
    subprocess.run(
        ["docker", "exec", container_name, "mkdir", "-p", "/etc/caddy/agent-denied"],
        capture_output=True, text=True, check=False,
    )
    subprocess.run(
        ["docker", "exec", "-i", container_name, "sh", "-c",
         "cat > /etc/caddy/agent-denied/index.html"],
        input=page, capture_output=True, text=True, check=False,
    )


def write_agent_chooser(container_name: str, devs: list[dict]) -> None:
    """Write the multi-developer 'choose your agent' page into Caddy.

    Only used when more than one developer exists: an unprefixed /auth/*
    request with no Referer can't be attributed to a specific agent, so we
    show a chooser instead of guessing. Kept as a file (rather than a Caddy
    `respond` body) so the HTML never has to survive Caddyfile quoting.
    """
    assert_same_project(container_name)
    links = "\n".join(
        f'    <li><a href="/agent/{html.escape(d["username"])}/login">'
        f'{html.escape(d.get("display_name") or d["username"])}</a></li>'
        for d in devs
    )
    page = f"""<!doctype html>
<meta charset="utf-8">
<title>Choose your agent</title>
<body style="font-family:system-ui;max-width:32rem;margin:15vh auto">
  <h1>Choose your agent</h1>
  <p>This sign-in link lost track of which agent you were using.
     Pick yours to continue:</p>
  <ul>
{links}
  </ul>
</body>
"""
    subprocess.run(
        ["docker", "exec", container_name, "mkdir", "-p",
         "/etc/caddy/agent-chooser"],
        capture_output=True, text=True, check=False,
    )
    subprocess.run(
        ["docker", "exec", "-i", container_name, "sh", "-c",
         "cat > /etc/caddy/agent-chooser/index.html"],
        input=page, capture_output=True, text=True, check=False,
    )


def write_via_caddy(container_name: str, filename: str, content: str) -> None:
    """Write a file into Caddy's Caddyfile.d directory by exec'ing into
    the Caddy container. Avoids bind-mount overlay issues on Bazzite.
    """
    assert_same_project(container_name)
    # Write to /etc/caddy/Caddyfile.d/<filename> inside Caddy container
    # Use a heredoc via docker exec to avoid shell escaping issues
    subprocess.run(
        ["docker", "exec", "-i", container_name, "sh", "-c",
         f"cat > /etc/caddy/Caddyfile.d/{filename}"],
        input=content,
        capture_output=True,
        text=True,
        check=False,
    )
