// Package emit turns a Registry into the YAML definitions ptn plan/apply reads.
//
// Spec §1 permits "frontends that emit IR" by name, and that is the legal basis
// for this package: the Go registry is such a frontend. What keeps it legal is
// what it CANNOT do. The emitter writes literal refs, literal parameters and
// flat lists -- there is no template, no conditional, no interpolation, and no
// way to express one. If this file ever grows a template engine, invariant 2
// has been broken from a new direction and the emitter is the bug.
//
// It also does not emit wiring. `on:` and `then:` are edges, hand-authored in
// YAML that references these tasks (invariant 3). Go owns what an action IS;
// YAML owns how actions are WIRED. Blurring that line is how this becomes a DSL.
//
// The YAML is written by a fixed template rather than a general encoder,
// deliberately: the drift gate compares bytes, and a fixed template has exactly
// one possible output for a given registry.
package emit

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/obsidura/pantheon-go/action"
	"github.com/obsidura/pantheon-go/kernel"
)

// Header is prepended to every generated file. It names the generator so that
// someone who finds a puzzling definition at 2am learns where it came from
// without having to ask.
const Header = "# GENERATED by ptn-gen from the pantheon-go registry. Do not edit.\n" +
	"# Source of truth is the Go action Spec; regenerate with `ptn-gen emit`.\n"

// File is one generated artifact.
type File struct {
	Path    string // relative to the output root
	Content []byte
}

// Definitions renders every registered action as a task definition, one file
// per action, plus the JSON Schema documents the refs point at.
func Definitions(reg *action.Registry) ([]File, error) {
	var files []File
	seenSchema := map[string]bool{}

	for _, e := range reg.Entries() {
		y, err := taskYAML(e)
		if err != nil {
			return nil, err
		}
		pkg, short := splitName(e.Spec.Name)
		files = append(files, File{
			Path:    filepath.Join("tasks", pkg, short+".yaml"),
			Content: y,
		})

		for ref, doc := range map[string]any{
			e.Spec.Input.String():  e.InputSchema,
			e.Spec.Output.String(): e.OutputSchema,
		} {
			if seenSchema[ref] {
				continue
			}
			seenSchema[ref] = true
			b, err := schemaYAML(ref, doc)
			if err != nil {
				return nil, fmt.Errorf("emit: schema %s: %w", ref, err)
			}
			files = append(files, File{
				Path:    filepath.Join("schemas", schemaFilename(ref)),
				Content: b,
			})
		}
	}

	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	return files, nil
}

// schemaYAML renders a registered Record schema as a definition file.
//
// A schema is a registry entry (spec §6), so it is a definition with a `kind:`
// like everything else -- not a loose .json file the loader would have to know
// about specially. `ptn plan` resolves every input:/output: ref against these.
//
// The document itself is emitted as compact JSON on one line. YAML is a
// superset of JSON, so flow style is valid YAML; and compact means one
// canonical spelling, which is what the drift gate needs. It is generated, so
// nobody reads it by eye anyway.
func schemaYAML(ref string, doc any) ([]byte, error) {
	parsed, err := kernel.ParseTypeRef(ref)
	if err != nil {
		return nil, err
	}
	compact, err := json.Marshal(doc)
	if err != nil {
		return nil, err
	}

	var b bytes.Buffer
	b.WriteString(Header)
	b.WriteString("\n")
	fmt.Fprintf(&b, "kind: schema\n")
	fmt.Fprintf(&b, "name: %s\n", yamlScalar(parsed.Name))
	fmt.Fprintf(&b, "version: %d\n", parsed.Version)
	fmt.Fprintf(&b, "document: %s\n", compact)
	return b.Bytes(), nil
}

// taskYAML renders one task definition.
func taskYAML(e *action.Entry) ([]byte, error) {
	s := e.Spec
	var b bytes.Buffer
	b.WriteString(Header)
	b.WriteString("\n")

	// kind: matches the Rust enum tag (spec §7). This file is a Task.
	fmt.Fprintf(&b, "kind: task\n")
	fmt.Fprintf(&b, "name: %s\n", yamlScalar(s.Name))
	fmt.Fprintf(&b, "version: %d\n", s.Version)
	fmt.Fprintf(&b, "summary: %s\n", yamlScalar(s.Summary))
	b.WriteString("\n")

	// runner: script -- a deterministic body (spec §4). The Go library is
	// script-only by design; agentic steps stay in the Python runner and are
	// wired as ordinary graph neighbours.
	b.WriteString("runner:\n")
	b.WriteString("  kind: script\n")
	b.WriteString("  runtime: go\n")
	fmt.Fprintf(&b, "  entry: %s\n", yamlScalar(s.Name))
	b.WriteString("\n")

	fmt.Fprintf(&b, "input: %s\n", yamlScalar(s.Input.String()))
	fmt.Fprintf(&b, "output: %s\n", yamlScalar(s.Output.String()))
	b.WriteString("\n")

	if len(s.Uses) > 0 {
		b.WriteString("uses:\n")
		uses := append([]action.ResourceUse(nil), s.Uses...)
		sort.Slice(uses, func(i, j int) bool { return uses[i].Name < uses[j].Name })
		for _, u := range uses {
			fmt.Fprintf(&b, "  - name: %s\n", yamlScalar(u.Name))
			verbs := append([]string(nil), u.Verbs...)
			sort.Strings(verbs)
			fmt.Fprintf(&b, "    verbs: [%s]\n", strings.Join(quoteAll(verbs), ", "))
		}
		b.WriteString("\n")
	}

	b.WriteString("policy:\n")
	fmt.Fprintf(&b, "  timeout: %s\n", durationYAML(s.Policy.Timeout))
	fmt.Fprintf(&b, "  retry: %d\n", s.Policy.Retry)
	fmt.Fprintf(&b, "  idempotent: %t\n", s.Policy.Idempotent)
	if s.Policy.Budget > 0 {
		fmt.Fprintf(&b, "  budget: %d\n", s.Policy.Budget)
	}

	// No `on:` and no `then:`. Wiring is authored by hand in YAML that
	// references this task; emitting an edge here would break invariant 3.

	return b.Bytes(), nil
}

// Write writes files under root, creating directories as needed.
func Write(root string, files []File) error {
	for _, f := range files {
		full := filepath.Join(root, f.Path)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(full, f.Content, 0o644); err != nil {
			return err
		}
	}
	return nil
}

// Check reports which generated files differ from what is on disk. This is the
// drift gate: CI regenerates and compares, so the committed YAML is the artifact
// of record and Go is only how it is produced. Without this, the two diverge and
// the definitions stop describing what actually runs.
func Check(root string, files []File) ([]string, error) {
	var drifted []string
	for _, f := range files {
		full := filepath.Join(root, f.Path)
		got, err := os.ReadFile(full)
		if os.IsNotExist(err) {
			drifted = append(drifted, f.Path+" (missing)")
			continue
		}
		if err != nil {
			return nil, err
		}
		if !bytes.Equal(got, f.Content) {
			drifted = append(drifted, f.Path+" (differs)")
		}
	}

	// Also catch orphans: a definition for an action that no longer exists is
	// worse than a missing one, because ptn apply would happily register it.
	want := map[string]bool{}
	for _, f := range files {
		want[filepath.Join(root, f.Path)] = true
	}
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return err
		}
		if !want[path] {
			rel, _ := filepath.Rel(root, path)
			drifted = append(drifted, rel+" (orphan: no action produces it)")
		}
		return nil
	})
	if err != nil && !os.IsNotExist(err) {
		return nil, err
	}
	sort.Strings(drifted)
	return drifted, nil
}

// ---------- scalar rendering ----------

// plainScalar matches strings safe to emit unquoted in YAML.
var plainScalar = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._@/-]*$`)

// yamlScalar quotes a string when it would not survive as a plain scalar.
// Conservative on purpose: over-quoting is invisible, under-quoting silently
// changes a value's type or truncates it at a colon.
func yamlScalar(s string) string {
	if s == "" {
		return `""`
	}
	if plainScalar.MatchString(s) && !isYAMLReserved(s) {
		return s
	}
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`).Replace(s) + `"`
}

// isYAMLReserved catches the words YAML 1.1 readers coerce to booleans. A
// summary of "no" that becomes false is the kind of bug that survives review.
func isYAMLReserved(s string) bool {
	switch strings.ToLower(s) {
	case "y", "n", "yes", "no", "true", "false", "on", "off", "null", "~":
		return true
	}
	return false
}

func quoteAll(ss []string) []string {
	out := make([]string, len(ss))
	for i, s := range ss {
		out[i] = yamlScalar(s)
	}
	return out
}

// durationYAML renders a duration as a Go-style string, e.g. "1m30s". Emitted
// as a quoted scalar so no YAML reader is tempted to parse it as sexagesimal.
func durationYAML(d time.Duration) string { return `"` + d.String() + `"` }

func splitName(name string) (pkg, short string) {
	if i := strings.Index(name, "."); i > 0 {
		return name[:i], name[i+1:]
	}
	return "_", name
}

func schemaFilename(ref string) string {
	return strings.NewReplacer("@", "_v", "/", "_").Replace(ref) + ".yaml"
}
